create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    gender varchar(255),
    field varchar(255),
    age Integer,
    primary key (id)
);

SELECT * FROM MEMBER;